### DISCUSSION TITLE
Propose alternative way to load plugins ( support local plugins )

### DISCUSSION THREAD

**Discussion by ThePlenkov** [cap-js/.github#12] [Ideas]
Hi!

As we remember some time ago we had the cds.plugins property where we could mention list of plugins.

Later on an [automatic plugin detection](https://cap.cloud.sap/docs/node.js/cds-plugins#cds-plugins) logic was introduced which scans package.json and finds all plugins with cds-plugin.js file in root. 

I see here few problems:
- It's not possible to use locally defined plugins without adding them as dependencies to package.json. This goes against the concept of npm workspaces when modules are available without directly adding them to dependencies.  In typescript we don't even need this - it's enough to resolve in tsconfig.json.
- If plugin by some reason brings problems - the only way to switch it off - is removing from package.json which is also not exactly what I want. I don't want to install/uninstall it - i want just to configure that certain plugin should not be in use.

Thefore I'd like to kindly ask to support cds.plugins option back ( via package.json or cdsrc.json ) which we can use like this ( in yaml just for better readability )

```yml
cds:
  plugins:
    # this is my local package and it's not available in package.json
   # instead i have there something like workspaces: [plugins/*] 
   # and @mylocal/some-plugin is stored in plugins/some-plugin
    - @mylocal/some-plugin
    # this plugin is resolved via package,json but i don't want it to be loaded
    - name: some-global-plugin
      disable: true
```

It may work in addition to plugins resolved with a current logic ( but respectig disable flag ).

What do you think about this?

Thanks!
